### PR TITLE
No changing direction in air

### PR DESCRIPTION
**Pull request by Regulator13**
## Number of Issue Fixed
- #146 #220 #228 #229 #230 #187 #232 #188 #233 #234 

### Changes Proposed in the Pull Request:
__Players can no longer change directions in mid-air__
- Once a player jumps, they may not switch directions, at best they can slow until they are falling straight down
- If a player jumps straight up or falls straight down, whichever direction they move first will be the direction they can continue moving, they cannot reverse to the other direction once they have picked a direction
- Trampolines allow players to change directions, but only if they are bouncing straight up and down (really not an exception to the rule)
- Jetpacks _while in use_ allow players to change directions
- Hang-gliders allow players to change directions
- Players may reverse direction after hanging onto a wall, e.g. if they jump to the right to hang onto a wall, if they let go, they can travel back to the left if they would like to

__New Jumping Method__
- Players now have a default jump "tap" of 2/3 their max jump (speed not height, more like 1/3 height)
- They can hold down on the jump button for up to 10 steps to make themselves jump higher
- Changed default jumps to match new method. Max jump is the same as before.
- If a player hits the bottom of a block they will stop their jump and begin falling to prevent "sticking" to roofs during the jump 

__Drag decreased from 0.3 to 0.15__
- The player can not effect direction in air much

__Improved ledge grabbing__
- Must now be within 4 pixels instead of 6
- ~Max speed of 5 falling or jumping up to grab.~
- Must be moving downward to grab
- Now grabs the step the player would pass the edge to eliminate jolt

__Added water_on button__
- The rain in the game can be turned off for testing, tutorial, or beginner learning purposes

__Added jetpack_on button__
- The jetpack can now be turned on or off (For competitive play)
- The jetpack will still spawn then be deleted to prevent levels from being scrambled by this option.

__Improved explosive blocks__
- Explosive blocks now have two timers
- The first is how long the player has to throw it
- If the player has thrown it, it will freeze in place (and turn red) and begin a second timer to give the player time to run
- When that timer reaches 0 it will explode

__Laser beams now shoot through all non-solid objects__

__Difficulty Slider__
- 5 difficulties: Beginner, Easy, Normal, Hard, Expert
- Changes platform generation in 2 ways
- Changes the chance a platform will spawn at any given level (100%, 87.5%, 75%, 62.5%, 50%)
- Changes how often mandatory platforms spawn ( 1 platform every 2, 3, 4, 5, or 6 blocks)
- The normal difficulty is exactly as the game has been played until now and is the default

__Wall Jumps!__
- A fun new maneuver that allows players to launch themselves off a wall by holding down on right action while jumping
- Currently no limit to the number of wall jumps that can be performed consecutively
- Due to the controls, works with pick axe
- Player will _not_ fire a fireball when they release the right action if they have at least _attempted_ a wall jump while holding down on the right action key.

__Down key to grab objects beneath the player__
- The player can now grab objects directly beneath him with the down key
- Works just like the left action grab, but it will not unstick a stuck block

__Resource changes__
- Moved obj_corpse from characters to level since they are closer to blocks then characters

__Minor changes/ Bug fixes__
- If you are close enough to grab a ledge, you will do so even if you are facing the wrong direction (you will automatically face the right direction).
- Fixed a bug where players would attempt to climb down non-climbable objects
- Fixed a bug causing particles to remain on the screen
- Fixed a bug where the player would jump again if they were holding down on the jump button when they hit the ground
- added a macro for HANGING_TOL
- Fixed a bug causing players not to grab onto the edge when climbing with objects
- Fixed a bug causing game options to not save properly
- Players will no longer ignite a block they are holding if they are picking up an item

### Known Problems
- Potentially a bug with the new climbing, I suspect it occurs when the player hits the ledge dead on.

### Notes for Reviewer
- The direction change update is a test, but after some playing I vote yes on it. If it is approved by another member it can be pushed through. It does not hinder play except making wrap-around jumps impossible which was a little unrealistic.
- I may later add an item options page for things like `jetpack_on` but right now this is the only one I feel people might want to turn off.

### CODE REVIEW

**Comment by Phabbits** [comment]
Before approving this pull request I would like to know if the current jumping height system is intended to be changed in the future to make it smoother, and if not an explanation why.

**Comment by Regulator13** [comment]
So I tested this looking for it and I didn't notice the second jump you're talking about. I looked very carefully and it did almost appear as though the player picked up speed for a step. The thing is, I thought about how to make the player jump and I thought this approach was the best one. Currently the player simply sets their vspeed to their jump height for each step the player holds down on the jump key, from a minimum of 1 step to a max of 10. The player remains a constant speed throughout the jump.

The second thought I had is maybe it looks that way because the gravity just starts applying after jump, but no, the gravity is applied after the speed is set so their shouldn't be any glitches

I think what it is is simply the player slowing down. The player travels up at a constant speed while holding down on the up key so when gravity begins to apply maybe it appears as a second jump.

I think that's okay. As I said, I didn't notice anything (and still I barely do). I think this is the best way to apply the variable jump because we want 2 things:

1. A small jump when the player just taps on the jump key
2. A predictable rise rate so the player can let go at the right time for their jump

I'm open to other solutions if you think you have one. The truth of the matter is it doesn't really look right because the player is deciding how high they will jump, _after_ they jump. However, I think that works for our game, deciding how high you will jump before you jump is a huge pain, and has some problems.

1. The lack of feedback, i.e. players have to guess how high their jump will be instead of just letting go of jump when they are high enough
2. It takes too long to go places and is kinda annoying.

Open to ideas if you have a better solution.

**Comment by afrey15** [comment]
I also noticed the issue once alerted to it. I think Gabe is right and it should be addressed. We can try to balance them out by slowing down their jump after a few steps, but there may be a better way. Isaiah, could you check out [this video](https://www.youtube.com/watch?v=cg4SyPSkqEo) and see what differences might cause it to be seamless in this example, but a problem in our game?

**Comment by Regulator13** [comment]
I really don't like videos explaining things because they take a long time to explain usually like a half page of pertinent information. The jolt is the gravity suddenly "kicking in" for the first time (well really the second gravity step, the `vspeed` is always `vspeed - gravity_incr` up until the player stops jumping and it becomes `vspeed - gravity_incr*2`) which is what I think you're seeing. I can try and smooth it out some. I'll make another commit

**Comment by Regulator13** [comment]
See if that helps at all

**Comment by afrey15** [comment]
Seems fixed!

**Comment by Phabbits** [comment]
Okay, it does appear to be smoother now. Still noticeable when holding down. I have no idea how this will affect others or game play in general without doing more testing. It could be easily ignored in actual games, I don't know. Since it's functioning as it was designed I say it is fine to let through, and we can adjust it later if needed.

Forgot to mention in my first review that there was still some climbing debug displaying in the output window.  Stating "Before" and "After." I do not think it is appropriate to have these debug output committed to main. Comment those out, or remove them and I would say we are good to go.

**Comment by Regulator13** [comment]
Before, after and wall jump debug messages are removed

**Comment by afrey15** [comment]
I have another request for this pull. Can you increase character friction once again? I have been able to recreate the sliding pretty easily. Can we put it at a number where it stopping will be instant so it won't be a problem?

**Comment by Regulator13** [comment]
This code has already been approved so you'll have to save that for the next one @afrey15

**Pull request merged**
