### PR TITLE
Piranhas can collect coins

### PR DESCRIPTION
**Pull request by Regulator13**
## Number of Issue Fixed
- #151 #153 #209 #197 #182 #194 #184 #38 

### Changes Proposed in the Pull Request:
- Piranhas can collect coins
- Changed default jump key to up for keyboard only controls

__Characters can move through blocks and items__
- To prevent from characters getting stuck, they can now move through all blocks and items
- They can still pick them up just like before
- Frozen and stuck blocks are still solid
- Blocks lying on the ground are not solid
- _Players can no longer jump off a block on the ground or a stack of blocks since they are not solid_

__Default join key for gamepad is now start__

__Patrols stop when they are stuck between two solid objects__
- They also stop if they would only move one step before turning around

__Improvements in aiming__
- All aiming methods now cause the fireball/iceball/thrown object to pass through the intersection of the line formed by the aiming direction and a circle 64 pixels in radius centered on the player
- Fireballs/iceballs now spawn in the middle of the player instead of the top corner
- Aiming with the mouse in/past the right wall is accurate now

__Mandatory spawning improvements__
- Initial block spawns, initial trampolines, and the heart will no longer spawn on top of other objects or each other

### Known Problems
- Players can still not climb a ledge if a block is on top, even if the block is not solid for them

### Notes for Reviewer
- The characters moving through blocks if for testing and consideration. If game speed or play-ability are deemed issues, I will revert the commit

### CODE REVIEW

**Comment by afrey15** [comment]
This is cool! I have been looking through your code and I think I have an easier way to do this if you are interested.

**Comment by afrey15** [comment]
I don't know if it would help or not, but we could potentially keep the blocks and patrols solid. I always liked stacking them, blocking bullets with them, and pushing them and stuff. I'm not sure whether getting stuck in them was a problem, but I guess I hadn't personally noticed it. My other idea was to try the `object_set_solid` and `object_get_solid` functions. I think we might be able to bypass your arrays, and use the built-in gml collision checking again like this. I have been studying it, but you would know better than me on this. It's a cool solution you have though.

**Comment by Regulator13** [comment]
What? You made an issue saying you should be able to pick up blocks just like you picked up trampolines, that is by walking through them. I knew you wanted this because you made the issue, the question was really for @Phabbits.

**Comment by afrey15** [comment]
Okay. Are you talking about issue #153? I don't think I mentioned blocks in that issue..

**Comment by Regulator13** [comment]
You can't get stuck in items, you just right click to pick them up. So I assumed you meant blocks

**Comment by afrey15** [comment]
No, I had an error where I picked up an item, stood on another item, and set that item down below me, I wasn't be able to move. That was why I made a bug report for it and that is why I described it like that in the steps to reproduce.

**Comment by Regulator13** [comment]
But you can just right click to equip the item and you'll be unstuck

**Comment by afrey15** [comment]
Wouldn't that be considered a workaround? I was wondering why this issue may be happening

**Comment by Regulator13** [comment]
Maybe in like a huge huge stretch of a way. You could publish the game with this and it would be fine.

**Comment by afrey15** [comment]
Do you know why the bug occurs by chance?

**Comment by Regulator13** [comment]
You can't push an item into another item so you can't move

**Comment by afrey15** [comment]
I thought you couldn't push items because you pass through them instead

**Comment by Regulator13** [comment]
Then it probably only happens when one of the two objects is only an item

**Comment by afrey15** [comment]
Could we making jetpacks, trampolines, etc.. function like items to prevent this?

**Comment by Regulator13** [comment]
I just tested it, the update fixes that

**Comment by afrey15** [comment]
Okay. Maybe we can find a way to not have to draw an array every step if we change the blocks back to solid objects.

**Comment by Regulator13** [comment]
I didn't change the solidity of the blocks and them being solid doesn't make players bounce off of them

**Comment by Regulator13** [comment]
Plus the blocks are the thing that actually needed fixing. If you get two blocks on you you're stuck and can't get out. Items can just be equipped

**Comment by afrey15** [comment]
If blocks are solid, you would not be able to get two stuck on you? Unless I am missing something?

**Comment by Regulator13** [comment]
They can be thrown onto you or you can pick them up

**Comment by afrey15** [comment]
How do you get stuck in a block in those instances? They always bounced off for me

**Comment by Regulator13** [comment]
What? Blocks have never bounced off of people. You can push blocks but people can throw them into you or you can push a block against a wall until it goes into you and grab another block. The point is it has happened many times, and I've never seen the item issue happen, probably because you can just equip them.

**Comment by afrey15** [comment]
In regards to pushing a block into a wall and then grabbing another block, I am curious how that would happen? Where would the other block come from?

**Comment by Regulator13** [comment]
It could spawn next to you, it's mostly throwing blocks that does it though. It's happened several times before though, and I'm sure you were playing a few times when it happened.

**Comment by Regulator13** [comment]
Yeah you won't get stuck if it's just one block

**Comment by afrey15** [comment]
Perhaps a thrown block could check for the collision type situation with a character and no arrays will be necessary

**Comment by Regulator13** [comment]
That would really be more of a hack, I'm not sure what you think is wrong with lists but I think you're exaggerating how bad they are. Data structures are _memory_ intensive more so than _processing_ and these lists are created, contain 1-3 object ids, then are immediately destroyed. I don't think they're slowing things down.

**Comment by afrey15** [comment]
Can you change blocks back to their unchanging solid state so I can test the improved functionality of your solution?

**Comment by Regulator13** [comment]
But that is the entire problem I was fixing! Making blocks not solid is the point of the commit.

**Comment by afrey15** [comment]
I think we had a large communication breakdown.. We agree I never suggested making blocks something you could pass through?

**Comment by Regulator13** [comment]
Sure, but that was the main point of the commit, it also fixed your item thing though which is why I included the issue. However the changes clearly say players can walk through blocks to avoid getting stuck, which I think is a good change. Just awaiting @Phabbits's review now

**Comment by afrey15** [comment]
Okay. I think this seems like a pretty serious change in gameplay to make without creating an issue about it.

**Comment by Regulator13** [comment]
Well I thought that was what your issue was about until today. I can make an issue.

**Comment by Regulator13** [comment]
Regulator13_2 presents a duplicate request without players being able to walk through blocks. Closing this

**Pull request closed without merging**
